// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVWOM5k1PpH1eBP5SE217eI7aFQoGb8fU',
    appId: '1:665860206246:web:baca234d5507e406394e67',
    messagingSenderId: '665860206246',
    projectId: 'cardy-de018',
    authDomain: 'cardy-de018.firebaseapp.com',
    storageBucket: 'cardy-de018.firebasestorage.app',
    measurementId: 'G-M4TD5VZ744',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMTRr1gLRxoehLJVsUIaiYMAE1rs1DA0',
    appId: '1:665860206246:android:3ab26cc1da5d23e5394e67',
    messagingSenderId: '665860206246',
    projectId: 'cardy-de018',
    storageBucket: 'cardy-de018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cwatJw0dJ4u6A_kWSuV8vRSLvtkFTbo',
    appId: '1:665860206246:ios:bc9ea1e35ee7cb38394e67',
    messagingSenderId: '665860206246',
    projectId: 'cardy-de018',
    storageBucket: 'cardy-de018.firebasestorage.app',
    iosBundleId: 'com.example.cardy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4cwatJw0dJ4u6A_kWSuV8vRSLvtkFTbo',
    appId: '1:665860206246:ios:bc9ea1e35ee7cb38394e67',
    messagingSenderId: '665860206246',
    projectId: 'cardy-de018',
    storageBucket: 'cardy-de018.firebasestorage.app',
    iosBundleId: 'com.example.cardy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVWOM5k1PpH1eBP5SE217eI7aFQoGb8fU',
    appId: '1:665860206246:web:cdbdce7a3ab5b0b3394e67',
    messagingSenderId: '665860206246',
    projectId: 'cardy-de018',
    authDomain: 'cardy-de018.firebaseapp.com',
    storageBucket: 'cardy-de018.firebasestorage.app',
    measurementId: 'G-LQ5LBGPB70',
  );
}
